all: main.cpp Student.cpp Student.h Lamport.cpp Lamport.h State.cpp State.h AlarmClock.cpp AlarmClock.h StateEnum.h MessageTag.h
	mpic++ main.cpp Student.cpp Lamport.cpp -o DrunkStudents.out

clean:
	rm -f *.out *.o *~
